baseURL = "/"
languageCode = "en-us"
title = "EasySpeak Online by Bay Language Institute"
theme = "minimal-bootstrap-hugo-theme"
DisablePathToLower = true

[permalinks]
  page = "/:filename/"

[params]

  description = ""
  includeBootstrapJs = true
  cookieConsent = true
  iphone_sizes = [ "120x120", "152x152", "180x180" ]
  favicon_sizes = [ "32x32", "128x128", "192x192" ]

[menu]

  [[menu.main]]
      identifier = "redeem-code"
      name = "Redeem code"
      url = "https://languagepanel.com/bli/code"
      target = "_blank"
      weight = 1

  [[menu.main]]
      identifier = "free-evaluation"
      name = "Free evaluation"
      url = "https://languagepanel.com/bli/callback"
      target = "_blank"
      weight = 2

  [[menu.main]]
      identifier = "faq"
      name = "FAQ"
      url = "/faq"
      weight = 3

  [[menu.main]]
      identifier = "student-login"
      name = "Student Login"
      url = "https://languagepanel.com/bli/student"
      cssClass = "button--login"
      weight = 20
